### ISSUE TITLE
IO40 and 41 as the serial ports of D0 cores have no output！

### ISSUE THREAD

**Issue by c-hamster** [bouffalolab/bouffalo_sdk#122]
I tried using IO40, 41 as serial ports for D0 cores. After modifying the IO mapping. The serial port does not have any output. What's wrong?

#elif defined(CPU_D0)
    /* sipeed m1s dock */
    bflb_gpio_init(gpio, GPIO_PIN_40, 21 | GPIO_ALTERNATE | GPIO_PULLUP | GPIO_SMT_EN | GPIO_DRV_1);//TXD
    bflb_gpio_init(gpio, GPIO_PIN_41, 21 | GPIO_ALTERNATE | GPIO_PULLUP | GPIO_SMT_EN | GPIO_DRV_1);//rxd

#endif

**Comment by c-hamster** [comment]
ps: Chip is bl808c

**Comment by sakumisu** [comment]
Default pinmux is xtal_32k. Please refer to reference manul.

**Comment by c-hamster** [comment]
你发的邮件我已经收到！谢谢！
