### ISSUE TITLE
WIFI & BLE support

### ISSUE THREAD

**Issue by kamejoko80** [bouffalolab/bouffalo_sdk#123]
Please support WIFI & BLE, binary libs are OK too at least we need connectivity features working.

**Comment by sakumisue** [comment]
done

**Comment by kamushadenes** [comment]
Appreciate!

For future reference: https://github.com/bouffalolab/bouffalo_sdk/tree/master/examples/wifi

**Comment by madushan1000** [comment]
@sakumisue looks like wifi/ble support is only added for bl616? is that correct?

**Comment by sakumisue** [comment]
yes

**Comment by madushan1000** [comment]
Is bl808 support going to added soon?

**Comment by sakumisue** [comment]
On the going.

**Comment by madushan1000** [comment]
Thanks!

**Comment by sakumisue** [comment]
You can see bl808 wifi in sipeed sdk currently.

**Comment by sakumisue** [comment]
The effort is to move into this sdk.

**Comment by kamejoko80** [comment]
Appreciated your quick response, thanks @sakumisue
