### ISSUE TITLE
examples/wifi are not working on Sipeed M0S Dock BL616

### ISSUE THREAD

**Issue by bvernoux** [bouffalolab/bouffalo_sdk#126]
examples/wifi are not working tested on Sipeed M0S Dock BL616
How to reproduce:
- Use https://github.com/bouffalolab/bouffalo_sdk/tree/master/examples/wifi/sta/wifi_http
- Build it with the toolchain and flash it (using bootloader)
  - Toolchain tested https://github.com/bouffalolab/toolchain_gcc_t-head_windows & https://github.com/bouffalolab/toolchain_gcc_t-head_linux
  - cd "path/examples/wifi/sta/wifi_http"
  - `make ninja CHIP=bl616 BOARD=bl616dk`
  - Enter Bootloader (keep BOOT pressed and connect USB-C to PC)
  - `make flash CHIP=bl616 COMX=COMPort`
  - All is ok (no error returned and flash is done with success)
- When connecting to the shell over UART (with an FTDI C232HM DDHSL-0 connected at 2MBauds) the shell is not working and everything seems frozen.
  - It is expected to have the shell access to enter the command to connect to the AP to test WIFI ... (like in example `wifi_sta_connect BL_TEST 12345678` ...)

For information on same board (Sipeed M0S Dock BL616) other examples like `examples/shell/shell_os` (which is used in wifi examples), `examples\peripherals\usbdev\usbd_msc_ram... `work perfectly with an FTDI C232HM DDHSL-0 used for Serial Port (2Mbauds by default) for logs/shell...

**Comment by bvernoux** [comment]
> M0s has no psram, so it fails.

Does there is a way to avoid using psram for WIFI example ? (especially to be compatible with Sipeed M0S Dock BL616...)

**Comment by sakumisue** [comment]
modify proj.conf, disable ` CONFIG_PSRAM`

**Comment by bvernoux** [comment]
Thanks the hint to disable CONFIG_PSRAM (CONFIG_PSRAM 0) in proj.conf work fine now the console is working 

Tested with https://github.com/bouffalolab/bouffalo_sdk/tree/master/examples/wifi/sta/wifi_http
(My router is not BL_TEST but it is the same on the real one)
```
bouffalolab />wifi_sta_connect BL_TEST 12345678
bouffalolab />wifi_http_test www.free.fr
bouffalolab />Http client task start ...
file [D:/_proj/__Lab_Tools/RISCV/Bouffalo_Lab_Dev/bl_mcu_sdk/components/os/freertos/queue.c]
func [xQueueSemaphoreTake]
line [1507]
( pxQueue )
vAssertCalled
```

Also `wifi_scanl`  fail
```
bouffalolab />wifi_scan
bouffalolab />Run WifiMgmr init first...
scan failed
```
free command provide following details:
```
bouffalolab />free
bouffalolab />total   free    alloc   mxblk   frnode  alnode
169672  161048  8624    160856  8       0
```

**Comment by bvernoux** [comment]
Thanks the hint to disable CONFIG_PSRAM (CONFIG_PSRAM 0) in proj.conf work fine now the console is working

Tested with https://github.com/bouffalolab/bouffalo_sdk/tree/master/examples/wifi/sta/wifi_http
(My router is not BL_TEST but it is the same on the real one)
wifi_sta_connect seems to fail (like anything related to wifi) see logs:
```
bouffalolab />wifi_sta_connect BL_TEST 12345678
bouffalolab />wifi_http_test www.free.fr
bouffalolab />Http client task start ...
file [D:/_proj/__Lab_Tools/RISCV/Bouffalo_Lab_Dev/bl_mcu_sdk/components/os/freertos/queue.c]
func [xQueueSemaphoreTake]
line [1507]
( pxQueue )
vAssertCalled
```

Also `wifi_scan` fail (even if I reboot the board and I do only that command)
```
bouffalolab />wifi_scan
bouffalolab />Run WifiMgmr init first...
scan failed
```

For information free command provide following details:
```
bouffalolab />free
bouffalolab />total   free    alloc   mxblk   frnode  alnode
169672  161048  8624    160856  8       0
```

**Comment by sakumisue** [comment]
WIFI does not start, so why do you input cmd?

**Comment by bvernoux** [comment]
Forget about my previous log I had disabled the wifi code to check the console works (and it was not working because of CONFIG_PSRAM 1) and I have forgotten to reenable it
I have reverted my change to the code and the WIFI work fine now thanks for all
My advise will be to change the CONFIG_PSRAM (CONFIG_PSRAM 0) in proj.conf for all examples to be compatible with basic dev board without PSRAM with BL616 like  the Sipeed M0S Dock BL616

**Comment by sakumisue** [comment]
Thanks, i will modify.

**Comment by sakumisue** [comment]
done.
