### ISSUE TITLE
Toolchain for Apple M1

### ISSUE THREAD

**Issue by beckmx** [bouffalolab/bouffalo_sdk#138]
This is not an issue (it was, not anymore) but I want to share with you, some steps I followed to configure my environment to be able to develop and flash under an Apple MacOS M1 machine, i uploaded a repo indicating my instructions:

https://github.com/beckmx/bouffalo_labs_mac_toolchain

Great work guys :) 
Greetings!

**Comment by sakumisu** [comment]
Yep, Thank you!
