### ISSUE TITLE
standard_dpi undefined

### ISSUE THREAD

**Issue by kimyj1503** [bouffalolab/bouffalo_sdk#143]
Hello. I tried to connect a 7" parallel RGB interface LCD to BL808.
When I defined `LCD_DPI_STANDARD` on `lcd_conf_user.h`, it says that `lcd_mipi_dpi_init_t` from `standard_dpi.c` is not defined.
I checked the `mipi_dbi` and `spi` codes and their `init_t` are all defined except for the `mipi_dpi`.

Can you please check if this is a mistake from my side? Thank you in advance.

**Comment by sakumisu** [comment]
do not support bl808
