### ISSUE TITLE
Hardware error in HBN_IRQ_STAT register

### ISSUE THREAD

**Issue by Jatsekku** [bouffalolab/bouffalo_sdk#158]
It seems that irq_rtc_state bit in HBN_IRQ_STAT resgister is not set up after wakeup from hibernate mode (level 0).
Can you confirm?

**Comment by Jatsekku** [comment]
It also seems that RTC wakeup isn't that reliable .
I was able to set up RTC and acomp as wakeup source and sometimes, RTC wasn't waking up the MCU but acomp still was able to do that. 
In such a case, RTC was still running (uptime was correct) so it looks like problem with RTC's alarm interrupt (HBN_TIME compare irq)

**Comment by sakumisu** [comment]
RTC irq status is invalid, this is a bug.
