### ISSUE TITLE
No UART Output in wifi_mqtt_pub example

### ISSUE THREAD

**Issue by berkutta** [bouffalolab/bouffalo_sdk#163]
Hello

I'm trying to get the `wifi_mqtt_pub` example running on the BL616. It builds fine, and I can flash it. But I don't get any output via Terminal.

Despite that, I get output via Terminal for the `helloworld` example. I don't know what the difference is.

```
make CHIP=bl616 BOARD=bl616dk
make CHIP=bl616 BOARD=bl616dk flash COMX=/dev/ttyUSB0
sudo picocom -b 2000000 /dev/ttyUSB0
```

**Comment by gamelaster** [comment]
did you tried different baudrate?

**Comment by berkutta** [comment]
Haven't found anything which should make the baudrate different between `wifi_mqtt_pub` and `helloworld`. But will check with the scope.

**Comment by berkutta** [comment]
Looks like there is no communication on the TXD pin.

`wifi_mqtt_pub` example:
![screenshot_no_com](https://github.com/bouffalolab/bouffalo_sdk/assets/11159719/43cef486-a2c0-4afa-9f2c-9270a3c0b176)

`helloworld` example:
![screenshot_com](https://github.com/bouffalolab/bouffalo_sdk/assets/11159719/99538931-220d-4da8-97ff-838573169b4d)

**Comment by sakumisu** [comment]
you must use bl618, mqtt must use psram

**Comment by sakumisu** [comment]
So if you use bl616, it will crash in psram init.

**Comment by berkutta** [comment]
Thanks, `wifi_tcp` example works :+1:
