### ISSUE TITLE
How to use SDIO2 on bl616

### ISSUE THREAD

**Issue by trevor403** [bouffalolab/bouffalo_sdk#168]
It looks like the bl602 exclusively used sdu as an SDIO2 slave interface. However `bl616_sdu.c` in the SDK looks like a stub when compared with the [bl_iot_sdk_matter](https://github.com/bouffalolab/bl_iot_sdk_matter) implementation.

Is the correct way to use the SDIO2 slave peripheral via `bflb_sdio2.c` and will there be an example like the `netbus_mgmr` component?

**Comment by sakumisu** [comment]
SDIO2 is special and need private sdh host driver, not for public

**Comment by trevor403** [comment]
I am more interested in `sdu` and how to use it on `bl616` as an SDIO Slave device.

**Comment by trevor-clickup** [comment]
Is it true that SDIO2 in Slave mode will never be publicly supported by the `bl616`

**Comment by trevor403** [comment]
So is this a private proprietary feature? Is it not actually offered and the marketing for this IC is incorrect? I am interested to know [Bouffalo Lab](https://en.bouffalolab.com/)'s response.

**Comment by gamelaster** [comment]
https://github.com/bouffalolab/bouffalo_sdk/tree/master/examples/peripherals/sdio2/sdio2_test
