### ISSUE TITLE
lmac154 component support

### ISSUE THREAD

**Issue by Jatsekku** [bouffalolab/bouffalo_sdk#173]
Hi,
I've seen there was support for lmac154, but it's no longer in master. Why it was removed?
https://github.com/bouffalolab/bouffalo_sdk/commit/d02d405d5428d46dc1a97fc0a552f631edbaa548

**Comment by sakumisu** [comment]
We do not test these in current sdk, you can copy and test by yourself.

**Comment by Jatsekku** [comment]
Okey, thanks
