### ISSUE TITLE
bl616 wifi monitor mode and frame injection

### ISSUE THREAD

**Issue by wojtess** [bouffalolab/bouffalo_sdk#178]
It is possible to use monitor mode and frame injection in bl616?
In [wifi_mgmr_ext.h](https://github.com/bouffalolab/bouffalo_sdk/blob/master/components/wireless/wifi6/inc/wifi_mgmr_ext.h#L82) there is struct called `wifi_mgmr_sniffer_item_t`, but there is no example or documentation how to use it.

**Comment by sakumisu** [comment]
Not support for you. It is private.

**Comment by wojtess** [comment]
documentation state that sniffer mode is public https://github.com/bouffalolab/bl_docs/blob/main/BL616_DS/en/BL616_BL618_DS_1.5_en.pdf
![image](https://github.com/bouffalolab/bouffalo_sdk/assets/49391462/ca542653-360e-4b9f-8c31-daf5713f9658)
