### ISSUE TITLE
Interrupts stop working if FreeRTOS is enabled

### ISSUE THREAD

**Issue by harbaum** [bouffalolab/bouffalo_sdk#181]
I am using SPI and USB on BL616 in the same project. Unfortunately interrupts won't fire anymore once I include FreeRTOS. This is nicely visible with the spi_int example. With FreeRTOS enabled the demo will still run but the interrupts stop working.

Is there a way to use e.g SPI interrupts in a FreeRTOS environment?

**Comment by sakumisu** [comment]
You should use spi int demo in your task, if you use demo before vTaskStartScheduler(), it fails.

**Comment by harbaum** [comment]
Thanks, that indeed makes the interrupts work!
