### ISSUE TITLE
Bouffalo SDK Build Log Flash/RAMs Usage 

### ISSUE THREAD

**Issue by WGR7** [bouffalolab/bouffalo_sdk#185]
Hi,

Please add to the final build log the memory usage of the builded binary.

Regards.

**Comment by gamelaster** [comment]
You can do it by yourself in CMakeLists.txt (sorry, on the phone, so I can't give more precise solution, but Google is our friend 😁 )

**Comment by WGR7** [comment]
It's better to add as a default to SDK.

**Comment by sakumisue** [comment]
Done
