### ISSUE TITLE
'bflb_device_get_by_id'这个函数有bug

### ISSUE THREAD

**Issue by Tliang4540** [bouffalolab/bouffalo_sdk#188]
`
        if ((bl616_device_table[i].dev_type == type) && (bl616_device_table[i].idx = idx)) {
            return &bl616_device_table[i];
        }
`
bl616_device_table[i].idx = idx应该是bl616_device_table[i].idx == idx吧

**Comment by sakumisu** [comment]
是的，这边是有错误的。不过这个api废掉了，没有用处

**Comment by Tliang4540** [comment]
> 是的，这边是有错误的。不过这个api废掉了，没有用处

为什么废掉了？只能用get_by_name了吗？

**Comment by sakumisu** [comment]
方便对接其他平台
