### ISSUE TITLE
Please update bouffalodevcube to 1.8.9

### ISSUE THREAD

**Issue by VynDragon** [bouffalolab/bouffalo_sdk#201]
Please update bouffalodevcube to 1.8.9

The version in the repository is 1.0.9, the latest version from https://dev.bouffalolab.com/download is 1.8.9 .

1.8.9 is majorly better for a lot of usages (for example, flashing without partitions and boot2), and the presence of 1.0.9 in the SDK induced me into thinking this was the latest version.

**Comment by sakumisu** [comment]
We do not use devcube, we use flashcube, this is not the same.
